import type { MediaSummary } from './media';

export const demoMedia = {
  featured: {
    mediaRef: 'demo:movie:dune-part-two',
    type: 'movie',
    title: 'Дюна: Часть вторая',
    originalTitle: 'Dune: Part Two',
    year: 2024,
    shortDescription:
      'Пол Атрейдес объединяется с фрименами и готовится отомстить заговорщикам, уничтожившим его семью.',
    poster: {
      url: 'https://placehold.co/600x900/29251f/f1f0ec?text=Dune',
      width: 600,
      height: 900,
    },
    backdrop: {
      url: '/images/demo/featured-desert-v1.png',
      width: 1664,
      height: 935,
    },
    genres: ['Фантастика', 'Драма', 'Приключения'],
    rating: {
      value: 8.2,
      scale: 10,
    },
  },
  severance: {
    mediaRef: 'demo:series:severance',
    type: 'series',
    title: 'Разделение',
    originalTitle: 'Severance',
    year: 2022,
    poster: {
      url: 'https://placehold.co/600x900/26282b/f1f0ec?text=Severance',
      width: 600,
      height: 900,
    },
    backdrop: {
      url: 'https://placehold.co/1600x900/26282b/f1f0ec?text=Severance',
      width: 1600,
      height: 900,
    },
    genres: ['Триллер', 'Драма'],
    rating: {
      value: 8.7,
      scale: 10,
    },
  },
  frieren: {
    mediaRef: 'demo:anime:frieren',
    type: 'anime',
    title: 'Провожающая в последний путь Фрирен',
    originalTitle: 'Sousou no Frieren',
    year: 2023,
    poster: {
      url: 'https://placehold.co/600x900/26302d/f1f0ec?text=Frieren',
      width: 600,
      height: 900,
    },
    backdrop: {
      url: 'https://placehold.co/1600x900/26302d/f1f0ec?text=Frieren',
      width: 1600,
      height: 900,
    },
    genres: ['Фэнтези', 'Драма', 'Приключения'],
    rating: {
      value: 9.0,
      scale: 10,
    },
  },
  oppenheimer: {
    mediaRef: 'demo:movie:oppenheimer',
    type: 'movie',
    title: 'Оппенгеймер',
    originalTitle: 'Oppenheimer',
    year: 2023,
    shortDescription: 'История физика Роберта Оппенгеймера и создания первой атомной бомбы.',
    poster: {
      url: 'https://placehold.co/600x900/302822/f1f0ec?text=Oppenheimer',
      width: 600,
      height: 900,
    },
    backdrop: {
      url: 'https://placehold.co/1600x900/302822/f1f0ec?text=Oppenheimer',
      width: 1600,
      height: 900,
    },
    genres: ['Биография', 'Драма', 'История'],
    rating: {
      value: 8.5,
      scale: 10,
    },
  },
  shogun: {
    mediaRef: 'demo:series:shogun',
    type: 'series',
    title: 'Сёгун',
    originalTitle: 'Shōgun',
    year: 2024,
    shortDescription:
      'Английский моряк оказывается в Японии на пороге масштабной борьбы за власть.',
    poster: {
      url: 'https://placehold.co/600x900/2c2925/f1f0ec?text=Shogun',
      width: 600,
      height: 900,
    },
    backdrop: {
      url: 'https://placehold.co/1600x900/2c2925/f1f0ec?text=Shogun',
      width: 1600,
      height: 900,
    },
    genres: ['Драма', 'История', 'Приключения'],
    rating: {
      value: 8.7,
      scale: 10,
    },
  },
  vinlandSaga: {
    mediaRef: 'demo:anime:vinland-saga',
    type: 'anime',
    title: 'Сага о Винланде',
    originalTitle: 'Vinland Saga',
    year: 2019,
    shortDescription:
      'Юный воин ищет мести, взрослея среди викингов и мечтая о мирной земле Винланд.',
    poster: {
      url: 'https://placehold.co/600x900/27302e/f1f0ec?text=Vinland+Saga',
      width: 600,
      height: 900,
    },
    backdrop: {
      url: 'https://placehold.co/1600x900/27302e/f1f0ec?text=Vinland+Saga',
      width: 1600,
      height: 900,
    },
    genres: ['Драма', 'История', 'Приключения'],
    rating: {
      value: 8.8,
      scale: 10,
    },
  },
  silentSphere: {
    mediaRef: 'demo:movie:silent-sphere',
    type: 'movie',
    title: 'Сфера молчания',
    originalTitle: 'Silent Sphere',
    year: 2024,
    poster: {
      url: 'https://placehold.co/600x900/1f2933/f1f0ec?text=Silent+Sphere',
      width: 600,
      height: 900,
    },
    genres: ['Фантастика', 'Триллер'],
    rating: { value: 7.6, scale: 10 },
  },
  horizonAshes: {
    mediaRef: 'demo:movie:horizon-ashes',
    type: 'movie',
    title: 'Пепел горизонта',
    originalTitle: 'Ashes of the Horizon',
    year: 2023,
    poster: {
      url: 'https://placehold.co/600x900/4a2718/f1f0ec?text=Horizon+Ashes',
      width: 600,
      height: 900,
    },
    genres: ['Драма', 'Фантастика'],
    rating: { value: 7.2, scale: 10 },
  },
  quietLands: {
    mediaRef: 'demo:movie:quiet-lands',
    type: 'movie',
    title: 'Тихие земли',
    originalTitle: 'Quiet Lands',
    year: 2022,
    poster: {
      url: 'https://placehold.co/600x900/3d4437/f1f0ec?text=Quiet+Lands',
      width: 600,
      height: 900,
    },
    genres: ['Драма', 'Приключения'],
    rating: { value: 7.1, scale: 10 },
  },
  lastSignal: {
    mediaRef: 'demo:movie:last-signal',
    type: 'movie',
    title: 'Последний сигнал',
    originalTitle: 'The Last Signal',
    year: 2024,
    poster: {
      url: 'https://placehold.co/600x900/211f2b/f1f0ec?text=Last+Signal',
      width: 600,
      height: 900,
    },
    genres: ['Детектив', 'Триллер'],
    rating: { value: 7.5, scale: 10 },
  },
  cityOnWater: {
    mediaRef: 'demo:series:city-on-water',
    type: 'series',
    title: 'Город на воде',
    originalTitle: 'City on Water',
    year: 2023,
    poster: {
      url: 'https://placehold.co/600x900/263238/f1f0ec?text=City+on+Water',
      width: 600,
      height: 900,
    },
    genres: ['Драма', 'Детектив'],
    rating: { value: 7.4, scale: 10 },
  },
  northernArchive: {
    mediaRef: 'demo:series:northern-archive',
    type: 'series',
    title: 'Архив северной станции',
    originalTitle: 'The Northern Archive',
    year: 2021,
    poster: {
      url: 'https://placehold.co/600x900/24313a/f1f0ec?text=Northern+Archive',
      width: 600,
      height: 900,
    },
    genres: ['Детектив', 'Фантастика'],
    rating: { value: 8.0, scale: 10 },
  },
  secondShore: {
    mediaRef: 'demo:series:second-shore',
    type: 'series',
    title: 'Второй берег',
    originalTitle: 'The Second Shore',
    year: 2020,
    poster: {
      url: 'https://placehold.co/600x900/26352f/f1f0ec?text=Second+Shore',
      width: 600,
      height: 900,
    },
    genres: ['Драма', 'Триллер'],
    rating: { value: 7.8, scale: 10 },
  },
  zeroHour: {
    mediaRef: 'demo:series:zero-hour',
    type: 'series',
    title: 'Нулевой час',
    originalTitle: 'Zero Hour',
    year: 2024,
    poster: {
      url: 'https://placehold.co/600x900/30282d/f1f0ec?text=Zero+Hour',
      width: 600,
      height: 900,
    },
    genres: ['Триллер', 'Криминал'],
    rating: { value: 8.1, scale: 10 },
  },
  glassGarden: {
    mediaRef: 'demo:anime:glass-garden',
    type: 'anime',
    title: 'Сад из стекла',
    originalTitle: 'Glass Garden',
    year: 2024,
    poster: {
      url: 'https://placehold.co/600x900/3b3040/f1f0ec?text=Glass+Garden',
      width: 600,
      height: 900,
    },
    genres: ['Фэнтези', 'Драма'],
    rating: { value: 8.4, scale: 10 },
  },
  beyondIce: {
    mediaRef: 'demo:anime:beyond-ice',
    type: 'anime',
    title: 'За гранью льда',
    originalTitle: 'Beyond the Ice',
    year: 2022,
    poster: {
      url: 'https://placehold.co/600x900/293943/f1f0ec?text=Beyond+Ice',
      width: 600,
      height: 900,
    },
    genres: ['Приключения', 'Фэнтези'],
    rating: { value: 7.8, scale: 10 },
  },
  redGate: {
    mediaRef: 'demo:anime:red-gate',
    type: 'anime',
    title: 'Врата багрового рассвета',
    originalTitle: 'Gate of the Crimson Dawn',
    year: 2021,
    poster: {
      url: 'https://placehold.co/600x900/432328/f1f0ec?text=Red+Gate',
      width: 600,
      height: 900,
    },
    genres: ['Фэнтези', 'Боевик'],
    rating: { value: 8.3, scale: 10 },
  },
  paperMoon: {
    mediaRef: 'demo:anime:paper-moon',
    type: 'anime',
    title: 'Бумажная луна над спящим городом',
    originalTitle: 'Paper Moon',
    year: 2020,
    poster: {
      url: 'https://placehold.co/600x900/302d42/f1f0ec?text=Paper+Moon',
      width: 600,
      height: 900,
    },
    genres: ['Драма', 'Фэнтези'],
    rating: { value: 7.7, scale: 10 },
  },
} satisfies Record<string, MediaSummary>;

export const demoMediaCatalog = Object.values(demoMedia);
